language: ruby

rvm:
  - "1.9.3"

branches:
  only:
    - master

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libicu-dev
  - sudo apt-get install -y cmake

before_script:
  # setup config
  - "cp config/config.yml.template config/config.yml"

script: bundle exec rspec spec
